spring:
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://${mysql.host}:3306/customerm
    password: '12345'
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
  application:
    name: customer-service
server:
  port: 8881
mysql:
  host: ${DOCKER_MYSQL_HOST:localhost}
